config/routes.rb
Rails.application.routes.draw do
  get 'transaction_entries/create'
  get 'transaction_entries/update'
  get 'transaction_entries/destroy'
  root "accounts#index"

  resources :accounts
  resources :budgets
  resources :transactions do
    member do
      resources :transaction_entries
    end
  end
end

app/models/budget.rb
class Budget
  include Mongoid::Document
  include Mongoid::Timestamps

  field :start_of_financial_year, type: Date
  field :end_of_financial_year, type: Date
  field :amount, type: BigDecimal
  field :currency, type: String

  belongs_to :account
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: %i[show edit update destroy]

  # GET /budgets or /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1 or /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets or /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to budget_url(@budget), notice: "Budget was successfully created." }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1 or /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to budget_url(@budget), notice: "Budget was successfully updated." }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1 or /budgets/1.json
  def destroy
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to budgets_url, notice: "Budget was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def budget_params
      params.require(:budget).permit(:start_of_financial_year, :end_of_financial_year, :account_id, :amount, :currency)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_budget.html.erb
<div id="<%= dom_id budget %>">
  <p>
    <strong>Start of Financial Year:</strong>
    <%= budget.start_of_financial_year %>
  </p>

  <p>
    <strong>End of Financial Year:</strong>
    <%= budget.end_of_financial_year %>
  </p>

  <p>
    <strong>Account:</strong>
    <%= budget.account.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= budget.amount %>
  </p>

  <p>
    <strong>Currency:</strong>
    <%= budget.currency %>
  </p>

</div>

app/views/budgets/_form.html.erb
<%= form_with(model: budget) do |form| %>
  <% if budget.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
        <% budget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_of_financial_year %>
    <%= form.date_field :start_of_financial_year %>
    <%= form.label :end_of_financial_year %>
    <%= form.date_field :end_of_financial_year %>
  </div>

  <div>
    <%= form.label :account_id, style: "display: block" %>
    <%= form.select(:account_id, Account.all.map{|a|[a.name, a._id]},{prompt: "Select parent account"},{class: "form-control"}) %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :currency, style: "display: block" %>
    <%= form.text_field :currency %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing budget</h1>

<%= render "form", budget: @budget %>

<br>

<div>
  <%= link_to "Show this budget", @budget %> |
  <%= link_to "Back to budgets", budgets_path %>
</div>

app/views/budgets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Budgets</h1>

<div id="budgets">
  <% @budgets.each do |budget| %>
    <%= render budget %>
    <p>
      <%= link_to "Show this budget", budget %>
    </p>
  <% end %>
</div>

<%= link_to "New budget", new_budget_path %>

app/views/budgets/new.html.erb
<h1>New budget</h1>

<%= render "form", budget: @budget %>

<br>

<div>
  <%= link_to "Back to budgets", budgets_path %>
</div>

app/views/budgets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @budget %>

<div>
  <%= link_to "Edit this budget", edit_budget_path(@budget) %> |
  <%= link_to "Back to budgets", budgets_path %>

  <%= button_to "Destroy this budget", @budget, method: :delete %>
</div>