config/routes.rb
Rails.application.routes.draw do
  get 'transaction_entries/create'
  get 'transaction_entries/update'
  get 'transaction_entries/destroy'
  root "accounts#index"

  resources :accounts
  resources :budgets
  resources :transactions do
    member do
      resources :transaction_entries
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:date, :memo, :ref, :balanced)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :memo, style: "display: block" %>
    <%= form.text_field :memo %>
  </div>

  <div>
    <%= form.label :ref, style: "display: block" %>
    <%= form.text_field :ref %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Date:</strong>
    <%= transaction.date %>
  </p>

  <p>
    <strong>Memo:</strong>
    <%= transaction.memo %>
  </p>

  <p>
    <strong>Ref:</strong>
    <%= transaction.ref %>
  </p>

  <p>
    <strong>Total Debits:</strong>
    <div id="total-debits"><%= transaction.total_debits %></div>
  </p>

  <p>
    <strong>Total Credits:</strong>
    <div id="total-credits"><%= transaction.total_credits %></div>
  </p>
</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transactions</h1>

<div id="transactions">
  <% @transactions.each do |transaction| %>
    <%= render transaction %>
    <p>
      <%= link_to "Show this transaction", transaction %>
    </p>
  <% end %>
</div>

<%= link_to "New transaction", new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/show.html.erb
<%= render @transaction %>
<h4>Entries </h4>
<hr width=75% />
<div id="new-transaction-entry-form">
  <%= render "transaction_entries/form" %>
</div>
<hr width=75% %>
<div id="transaction-entries">
  <% @transaction.transaction_entries.each do |transaction_entry| %>
    <%= render "transaction_entries/transaction_entry", transaction_entry: transaction_entry %>
  <% end %>
</div>
<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>